version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stock
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend

  nestjs_app:
    build:
      context: ./backend
      dockerfile: Dockerfile # Укажите имя Dockerfile для NestJS
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_DATABASE=stock
    networks:
      - backend

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Укажите имя Dockerfile для React и Nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - nestjs_app
    networks:
      - backend

networks:
  backend:
    driver: bridge
